version: '3.9'

networks:
  bridge: 
    driver: bridge

services:
  zookeeper:
    image: confluent/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT: 32181
      - ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bridge
    aliases:
      - zookeeper

  kafka:
    image: confluent/cp-kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID: 1
      - KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      - JMX_PORT: 9999
    networks:
      - bridge
    aliases:
      - kafka

  kafka-producer:
    image: kafka-producer
    depends_on:
      - kafka
    environment:
      KAFKA_SERVER: 'kafka:9092'
      ZOOKEEPER_SERVER: 'zookeeper:32181'
      PRODUCER_INTERVAL: 100
    networks:
      - bridge

  flink-producer:
    image: flink-producer
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER: 'kafka:9092'
      - ZOOKEEPER_SERVER: 'zookeeper:32181'
      - PRODUCER_INTERVAL: 100
    networks:
      - bridge

  generate-data:
    image: generate-data
    depends_on:
      - postgres
    networks:
      - bridge

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES=postgre
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=postgre
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - 5432:5432
    networks:
      - bridge

volumes:
  settings:
  data:

